name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # build website
      - name: Build
        run: npm run build

      # push the generated content into the `main` (former `master`) branch.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main # if your main branch is `master` use that here.
          publish_dir: ./dist
